### ISSUE TITLE
Using numeric comparison for non-numeric values

### ISSUE THREAD

**Issue by leonidr** [TheDMSGroup/mautic-eb#2]
AWS instance id has following format "i-1234567890abcdef0" and can't be copared using numeric comparison.

So following line will produce:  [: i-1234567890abcdef0: integer expression expected

https://github.com/TheDMSGroup/mautic-eb/blob/bdb5a887cccc45a502c71b2fdeb70dbf96710b89/scripts/aws-eb-cron.sh#L83

**Comment by heathdutton** [comment]
Good catch. Fixing.
