### ISSUE TITLE
Mautic's settings different between nodes

### ISSUE THREAD

**Issue by zero-one-devteam** [TheDMSGroup/mautic-eb#80]
## Description:
When changing a parameter in Mautic's setting that isn't defined in parameters_local.php it won't be "synced" between cluster nodes. Shouldn't all settings been shared via EFS volume between the nodes?

Mautic-Version: 2.15.0
PHP: 7.2

### Steps to reproduce:
1. Change a Mautic setting (e.g. CORS or MessageQueue)
2. Setting is only changed on current cluster node.

**Comment by heathdutton** [comment]
The local.php file is in the EFS mount and therefore shared between nodes. parameters_local.php is for settings that override those settings via env variables.

**Comment by heathdutton** [comment]
This happens here: https://github.com/TheDMSGroup/mautic-eb/blob/dev/.ebextensions/60_io.config#L72-L73

Note, because of opcache settings, a setting change like this can take up to 5 minutes to percolate globally across all nodes.

**Comment by zero-one-devteam** [comment]
Ah, good to know, thanks for pointing that out.
