### ISSUE TITLE
Prevent https redirection

### ISSUE THREAD

**Issue by zero-one-devteam** [TheDMSGroup/mautic-eb#84]
## Description:
When running on AWS with Cloudfront, I would like the EB Loadbalancer to only listen to http. It seems that the nodes automatically redirect http to https so that the health checks fail. Is there any option to prevent the redirection on the nodes (I did not found any config file, mayba Mautic is doing this?)

**Comment by zero-one-devteam** [comment]
Ah, I got it. If you set APP_URL to https://something there will always be a redirect. So, best practice in my case would be to set it only to the hostname (without any protocol), right?

**Comment by heathdutton** [comment]
I'd recommend enabling https with your load balancer config, and/or adding Cloudflare in front of your app for flexible SSL. You could also set the health check to hit a favicon.ico because health check in EB is usually  for testing apache is functioning more than testing your app is up and ready.

**Comment by zero-one-devteam** [comment]
Why would you prefer Cloudflare and not use Cloudfront? With Cloudfront one has a seamlessly integrated solution (custom ssl included) ...

**Comment by heathdutton** [comment]
Cloudflare has a wider feature set and we've been using its features (firewall/rate-limiting/caching/dns/etc) company-wide for years for apps both in and out of AWS.

Have nothing against Cloudfront, except that we aren't currently using it for much.
