### ISSUE TITLE
Themes on efs?

### ISSUE THREAD

**Issue by zero-one-devteam** [TheDMSGroup/mautic-eb#92]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 
| Question? | Yes

## Description:
Currently, themes are stored locally on the nodes. Should we link the themes directory to EFS so that themes files become available across all nodes? Otherwise we cannot use Mautic's GUI but have to deploy themes ...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2

**Comment by heathdutton** [comment]
You could symlink and rsync /mautic/themes exactly as /mautic/media is done in /.ebextensions/60_io.config This way new additions to core override customizations, but you can still manually add your own and share across nodes.

We welcome a PR on this.
We do not use custom themes ourselves, so this isn't something that affects us.

**Comment by zero-one-devteam** [comment]
This way was exactly as I did it - I just wanted to make sure it’s the right way. I will make a PR.
