### ISSUE TITLE
Tracking script inserts values in extended fields

### ISSUE THREAD

**Issue by zero-one-devteam** [TheDMSGroup/mautic-eb#97]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | possible bug
| Feature request? | 
| Enhancement? | 

## Description:
I‘ve upgraded to 2.15.1 and I am using extended fields. Inserting and updating values work perfect via api. But when using the mtc.js tracking script, every pageview inserts a number in each extend field (like 23, 24). This only happens with extended fields not with contact fields. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 

### Steps to reproduce:
1. activate extended field plugin
2. using tracking script on the website mtc.js
3. Mautic inserts numbers in each extended field
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by heathdutton** [comment]
Did you have this issue before upgrading to 2.15.1? We haven't released mautic-extended-field for 2.15.1 yet, nor mautic-eb.  We are intentionally behind the official release till such new BC/incompatibilities can be resolved.

Let's re-open this on the https://github.com/TheDMSGroup/mautic-extended-field repo

**Comment by zero-one-devteam** [comment]
I not 100% sure if the problem exists before 2.15.1 as I tested a lot but not tracking together with extended fields ... But as I did not make a lot of other changes it may be related with 2.15.1

**Comment by zero-one-devteam** [comment]
I will re-open this at the appropriate repo.
